spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: Anup@2242
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

global:
  message: Welcome to customer service dev environment!!

server:
  port: 8082
