global:
  message: Welcome to customer service dev environment!!
server:
  port: 8802
message: Hello from Dev!
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/cust_dev
   username: root
   password: Anup@2242
jpa
  hibernate:
    ddl-upto: update
  show-sql: true
