global:
  message: Welcome to customer service dev environment!!

server:
  port: 8802

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: Anup@2242

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
