global:
  message: Welcome to customer service production environment!!
server:
  port: 8803
message: Hello from Production!
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/cust_prod
   username: root
   password: Anup@2242
jpa
  hibernate:
    ddl-upto: update
  show-sql: true
