global:
  message: Welcome to order service dev environment!!
server:
  port: 8802
message: Hello from Order Dev!
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/order_dev
   username: root
   password: Anup@2242
jpa
  hibernate:
    ddl-upto: update
  show-sql: true
