global:
  message: Welcome to order service production environment!!
server:
  port: 8805
message: Hello from Production!
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/order_prod
   username: root
   password: Anup@2242
jpa
  hibernate:
    ddl-upto: update
  show-sql: true
